apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  labels:
    app: doctor-service
spec:
  type: ClusterIP
  selector:
    app: doctor-service
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
