apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
  labels:
    app: doctor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          image: doctor-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8083"
            - name: DB_PATH
              value: "/app/data/doctor-service.db"
          volumeMounts:
            - name: doctor-data
              mountPath: /app/data
      volumes:
        - name: doctor-data
          emptyDir: {}
