apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
  labels:
    app: telemedicine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: telemedicine-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: PORT
              value: "8085"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: telemedicine-secret
                  key: MONGO_URI
            - name: JITSI_BASE_URL
              value: "https://meet.jit.si"
