version: '3.9'

services:

  doctor-service:
    build: ./backend/doctor-service
    container_name: doctor-service
    ports:
      - "8082:8082"
    environment:
      - PORT=${DOCTOR_PORT}
      - MONGO_URI=${DOCTOR_MONGO_URI}
    volumes:
      - doctor_data:/app/data

  telemedicine-service:
    build: ./backend/telemedicine-service
    container_name: telemedicine-service
    ports:
      - "8085:8085"
    environment:
      - PORT=${TELEMEDICINE_PORT}
      - MONGO_URI=${TELEMEDICINE_MONGO_URI}
      - JITSI_BASE_URL=https://meet.jit.si

volumes:
  doctor_data:
  telemedicine_data: