version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    container_name: medicare-api-gateway
    ports:
      - '3000:3000'
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth-service
      - ai-symptom-service
    networks:
      - medicare-network

  auth-service:
    build: ./auth-service
    container_name: medicare-auth-service
    ports:
      - '3001:3001'
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongo-auth
    networks:
      - medicare-network

  ai-symptom-service:
    build: ./ai-symptom-service
    container_name: medicare-ai-symptom-service
    ports:
      - '3002:3002'
    env_file:
      - ./ai-symptom-service/.env
    depends_on:
      - mongo-auth
    networks:
      - medicare-network

  mongo-auth:
    image: mongo:6
    container_name: medicare-mongo-auth
    ports:
      - '27017:27017'
    volumes:
      - mongo-auth-data:/data/db
    networks:
      - medicare-network

networks:
  medicare-network:
    driver: bridge

volumes:
  mongo-auth-data:
